@startuml
left to right direction

actor Applicant as a
actor Employer  as e

usecase "Create vacancy"      as cv
usecase "Edit vacancy"        as ev
usecase "Delete vacancy"      as dv
usecase "Close vacancy"       as clv
usecase "View vacancy"        as vv

usecase "Edit applicant profile" as ep
usecase "Search vacancies"    as sv
usecase "Apply for vacancy"   as afv

usecase "View application list for vacancy" as vapps
usecase "View applicant" as vap
usecase "View employer" as vep

a --> vv
a -> ep
a --> afv
a -> sv
a -> vep

cv <-- e
ev <-- e
dv <-- e
vv <-- e
clv <-- e
vap <- e
vapps <- e


@enduml
